apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: n8n
  labels:
    app.kubernetes.io/name: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-internal
  target:
    name: postgres-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: POSTGRES_PASSWORD

