apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-internal
  target:
    name: n8n-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: N8N_BASIC_AUTH_USER
      remoteRef:
        key: n8n
        property: N8N_BASIC_AUTH_USER
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        key: n8n
        property: N8N_BASIC_AUTH_PASSWORD
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: N8N_WEBHOOK_SECRET
      remoteRef:
        key: n8n
        property: N8N_WEBHOOK_SECRET

