apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-internal
  labels:
    app.kubernetes.io/part-of: n8n
spec:
  provider:
    kubernetes:
      # ESO will read source secrets from this namespace
      remoteNamespace: eso-secrets
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets

