name: Build and Push n8n (multi-arch)

on:
  workflow_dispatch:
    inputs:
      n8n_ref:
        description: "n8n repo ref (tag/branch/sha)"
        required: true
        default: "stable"
  push:
    tags:
      - 'release-*'

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/n8n

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Checkout n8n source
        uses: actions/checkout@v4
        with:
          repository: n8n-io/n8n
          ref: ${{ github.event.inputs.n8n_ref || 'stable' }}
          path: n8n-src

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: meta
        run: |
          if [ -f n8n-src/packages/cli/package.json ]; then
            VERSION=$(jq -r '.version' n8n-src/packages/cli/package.json)
          else
            VERSION=$(date +%Y.%m.%d)-${{ github.sha }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "ref=${{ github.event.inputs.n8n_ref || 'stable' }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: n8n-src
          file: n8n-src/docker/images/n8n/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE }}:${{ steps.meta.outputs.ref }}
          build-args: |
            N8N_VERSION=${{ steps.meta.outputs.version }}

